### ISSUE TITLE
Cran issue

### ISSUE THREAD

**Issue by stephlocke** [lockedata/ibmsunburst#13]
Dear maintainer,

Please see the problems shown on
<https://cran.r-project.org/web/checks/check_results_ibmsunburst.html>.

Please correct before 2022-04-24 to safely retain your package on CRAN.

Best,
-k

**Comment by stephlocke** [comment]
Dear maintainer,

Please see the problems shown on
<https://cran.r-project.org/web/checks/check_results_ibmsunburst.html>.

Please correct before 2022-05-08 to safely retain your package on CRAN.

Note that this will be the *final* reminder.

Best,
-k

**Comment by osheen1** [comment]
Closing as ibmsunburst has been reinstated on CRAN!
