### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by timelyportfolio** [lockedata/ibmsunburst#2]
I left comments for some tests that I think should be added. We need to start writing tests that make sure the ibmsunburst() function works as expected.
https://github.com/lockedata/ibmsunburst/blob/master/tests/testthat/tests_basic.R

Tests in a similar package: https://github.com/timelyportfolio/sunburstR/blob/master/tests/testthat/test-basic.R

**Comment by timelyportfolio** [comment]
@maelle fantastic work on the tests :100: ; thanks!

6417fc7756a2a7c14a098bb04134751dd40d083c
ae741391405620581c59807500831d18fa4500f0
a8c54343c5120a0cdacb281ca6a69eef2be588e1

**Comment by timelyportfolio** [comment]
If we want to get really serious about this we can add visualization regression testing as RStudio has done with [leaflet](https://github.com/rstudio/leaflet/blob/master/scripts/viztest_testing_notes.md).  My vote is this is probably not necessary at this stage.

**Comment by maelle** [comment]
Thank *you*, adding tests below the comments was a joy, it all worked and having a roadmap made it very easy! I guess we can close this, I'll open another issue for more elaborate testing.
