### ISSUE TITLE
Use the vignette to explore how to do an API call and visualise the results

### ISSUE THREAD

**Issue by stephlocke** [lockedata/ibmsunburst#6]
We should show people in the vignette how to do an API call to get data, what sort of things they may need in order to do so, and how to interpret the resulting chart.

Resources
- Example workflow: https://gist.github.com/stephlocke/053e047b9a41dcb1fd9fe181e5b5ba1c
- API docs: https://www.ibm.com/watson/developercloud/personality-insights/api/v3/
- About vignettes http://r-pkgs.had.co.nz/vignettes.html

Things to remember
- Any extra libraries like httr mentioned in a vignette need to be added to the DESCRIPTION in the Suggests section

**Comment by maelle** [comment]
I added your code as unevaluated chunk. I wonder whether this is enough for now.

**Comment by stephlocke** [comment]
Fab, thanks!
